### ISSUE TITLE
PYRA on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [THU-MIG/PYRA#1]
Hello @Bostoncake 🤗

I'm Niels and I work on computer vision at Hugging Face. I see your paper is accepted as ECCV Poster, congratulations! I will index it here https://huggingface.co/papers/2403.09192 at paper pages. The paper page lets people discuss about your paper and lets them find artifacts about it (your model for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the model you've pre-trained with this technique on https://huggingface.co/models? I see you're using Google Drive for it. Hosting on Hugging Face will give you more visibility.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.
You can also build a demo to your model on [Spaces](https://huggingface.co/spaces) we can provide you an A100 grant.

What do you think?

**Comment by Bostoncake** [comment]
Hi @NielsRogge,

Sorry for the late reply. Thank you so much for your congratulations and for indexing our paper on the Hugging Face platform. We appreciate the visibility and opportunities it provides.

Regarding your suggestion to host the model on Hugging Face, I’d like to clarify that our PYRA method is specifically a fine-tuning technique applied to pre-trained models for downstream tasks rather than a pre-training approach. The models available on Google Drive are pre-trained models for reproducing the fine-tuning experiments outlined in our paper. Therefore, we do not have any model weights ready for deployment at this time.

However, we would be happy to host our code on huggingface if that’s possible, and we appreciate any guidance on that front.

Thank you again for your support and assistance!

**Comment by NielsRogge** [comment]
I see, thanks for clarifying :)

Nevertheless, we hope that researchers like you upload their artifacts to the hub in the future for easier discoverability/accessilbility :) it can have a massive impact on the visibility of your work.

Regarding hosting the code, sure that is possible, although the hub is mostly meant to host models, datasets and demos (in the form of a Gradio, Streamlit or Docker demo on Spaces).

Do you have any future works that you plan to release anytime soon? We're happy to assist with the integration :)

**Comment by Bostoncake** [comment]
We currently don't have any plans on releasing models yet. But we are doing some research on pre-training and fine-tuning models aimed for specific applications. Maybe we have opportunities to collaborate in the future:) 

Thank you for your support!

**Comment by NielsRogge** [comment]
Sounds good, thanks for the update!
